server:
  port: 9091
  
spring:
  application:
    name: Account-Service
  jpa:
    hibernate:
      ddl-auto: update
      
  datasource:
    url: jdbc:mysql://localhost:3306/account-management-db
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jackson:
    serialization:
      fail-on-empty-beans: false
      
      
  config:
    import: "optional:configserver: http://localhost:9093" 
